version: '3.9'
services:
  nextapp:
    container_name: nextapp
    image: foreverflyyy/nextjs
    volumes:
      - type: bind
        source: .
        target: /client
    build: .
    ports:
      - 3000:3000
  nestapp:
    container_name: nestapp
    image: foreverflyyy/nestjs
    volumes:
      - type: bind
        source: .
        target: /server
    build: .
    ports:
      - 3001:3001
    environment:
      MONGODB_ADMINUSERNAME: root
      MONGODB_ADMINPASSWORD: example
      MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - type: volume
        source: mongodata
        target: /data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
volumes:
  mongodata: